services:
  api:
    build: .
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  postgres_data:
    driver: local